modLoader = "javafml"
loaderVersion = "${neo_forge_loader_version}"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors_neo_forge}"
description = "${mod_description}"

#logoFile = ""

[[dependencies.${ mod_name }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_name }]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_name }]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_name}.mixins.json"

[[mixins]]
config = "${mod_name}.neoforge.mixins.json"
